### PR TITLE
Use compatibility profile for OpenGL bindings

### PR DESCRIPTION
**Pull request by nox**
We need POINT_STRIPE in Servo.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/gleam/174)

### CODE REVIEW

**Comment by kvark** [comment]
@nox I don't think it's a good idea to rely on GL compatibility profile in this day and age, especially for an experimental (future-looking!) browser like Servo. For example, MacOS would only give you compatibility profile with GL 2.1 context, which we can't use in WR anyway. Could you reconsider the need for POINT_STRIPE?

**Comment by nox** [comment]
No I can't, Servo currently uses GL 2.1 for WebGL 1.0 contexts and I'm not going to change that right now.

**Comment by nox** [comment]
https://github.com/servo/servo/pull/21961
https://searchfox.org/mozilla-central/source/dom/canvas/WebGLContextValidate.cpp#565-571

**Comment by nox** [comment]
Note also that Firefox enables `POINT_STRIPE` with 3.0 contexts too, and with 3.1 contexts which support the `ARB_compatibility` extension.

https://searchfox.org/mozilla-central/source/gfx/gl/GLContext.cpp#686-692

**Comment by kvark** [comment]
uh, I see

**Pull request merged**
