### PR TITLE
Add support for the client storage extension

### PR DESCRIPTION
**Pull request by jrmuizel**
This change is [Reviewable](https://reviewable.io/reviews/servo/gleam/126)

### CODE REVIEW

**Comment by jrmuizel** [comment]
I've filed https://github.com/brendanzab/gl-rs/issues/429 about adding a private field to the generated structs. We might as well try to do that first so we only need to bump the major version now and not next time.

**Comment by jrmuizel** [comment]
I've filed https://github.com/brendanzab/gl-rs/issues/429 about adding a private field to the generated structs. We might as well try to do that first so we only need to bump the major version now and not next time.

**Comment by kvark** [comment]
Thanks! Could you rebase and squash please?
I think we'll still need to wrap up those `ffi` calls (to client storage and such) in rusty functions, but that would be non-breaking follow-ups.

**Comment by jrmuizel** [comment]
I've dropped the version change commit now that gl_generator has been updated to include a private field.

**Comment by kvark** [comment]
@jrmuizel let's switch `gl_generator` dependency to 0.6.1 and bump the minor version (of `gleam`) here?

**Comment by jrmuizel** [comment]
Done

**Comment by kvark** [comment]
Thanks! Squash it, please?

**Comment by jrmuizel** [comment]
Why? Aren't they separate things?

**Comment by kvark** [comment]
It seems weird to have a multiple micro commits (one liners) following each other. Just because they can be treated independently doesn't mean they should? Anyhow, I don't have strong feelings about this.

**Pull request merged**
