### PR TITLE
Change android bindings to use ES3.0.

### PR DESCRIPTION
**Pull request by glennw**
It was inevitable...

---
This change is [Reviewable](https://reviewable.io/reviews/servo/gleam/69)

### CODE REVIEW

**Comment by pcwalton** [comment]
I'm OK with this, but I think @larsbergstrom should sign off.

**Comment by glennw** [comment]
@pcwalton Yep, that's fine.

For now, this is to get demos that @larsbergstrom is working on running - there are associated patches that remove the ES2 path from WR/servo to do this. Eventually I'd like to merge this properly, but we can hold off for a bit (and use a local override for android WR demos) if we want to discuss this further.

**Comment by larsbergstrom** [comment]
I am OK with this, based on my knowledge of the target Android devices.

@michaelwu Does this also seem reasonable to you, or are there important parts of the Android ecosystem you're aware of that we'd be cutting off by requiring GLES3?

**Comment by pcwalton** [comment]
We're cutting off roughly 50% of the current Android market, plus devices like the Raspberry Pi 1/2/3. This is changing fast, though. OpenGL ES 2 is very old at this point.

**Comment by michaelwu** [comment]
I think pcwalton covers it for Android. From the SoCs I've seen on Gonk, it seems like only modern QC (Adreno) SoCs have sufficient 3.0 support. There's still a lot of SoCs with old Mali 4xx (2.0 only) so you'd likely cut off support for a lot of the really cheap SoCs people like to use for slower things. I'm sure that'll fix itself in time..

**Comment by michaelwu** [comment]
Hmm, I've actually found at least one new 64 bit SoC shipping with Mali 450 - Amlogic S905. Guess ARM hasn't given up on it yet?

**Comment by larsbergstrom** [comment]
Chatted more with @metajack about this, and we're comfortable with this change. If ES2 support becomes something we need in the future, we'd rather take on the work of a backport to run on old hardware over trying to keep GLES2 and a completely different set of rendering paths working while WebRender is still under rapid development.

@bors-servo r+

**Pull request merged**
