### PR TITLE
Implement get_renderbuffer_param_iv

### PR DESCRIPTION
**Pull request by brainlessdeveloper**
I think this is necessary for https://github.com/servo/servo/issues/20514

I didn't find a way to run tests or anything similar on this repo, so I also can't be sure whether the PR is correct.

https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.7
https://www.khronos.org/registry/OpenGL/specs/es/2.0/es_full_spec_2.0.pdf#nameddest=section-6.1.3

---
This change is [Reviewable](https://reviewable.io/reviews/servo/gleam/162)

### CODE REVIEW

**Comment by brainlessdeveloper** [comment]
r?

**Comment by kvark** [comment]
LGTM, thank you!
@bors-servo r+

**Comment by brainlessdeveloper** [comment]
Do I need to tag or something? I don't think I'm allowed to. I need to use the new code on one of my Servo PRs.

**Comment by kvark** [comment]
https://crates.io/crates/gleam/0.4.33

**Comment by brainlessdeveloper** [comment]
@kvark awesome, thanks!

**Pull request merged**
