### PR TITLE
Introduce get_blend_color

### PR DESCRIPTION
**Pull request by MaximilianDauner**
Hello @nox ,
added get_blend_color for the issue: https://github.com/servo/servo/issues/20536
Hope everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/gleam/165)

### CODE REVIEW

**Comment by kvark** [comment]
It appears to me that #164 will provide the necessary lower level accessors.

**Comment by MaximilianDauner** [comment]
Hello @kvark ,
you' re right , I can use get_float_v.
Since this issue has not yet been merged, I can not really finish servo/servo#20536 or ?

**Comment by kvark** [comment]
Let's ping @nox and ask about the status of that PR

**Comment by nox** [comment]
This is now unblocked, but this PR is now unnecessary thanks to #164.

**Pull request closed without merging**
