### PR TITLE
Add explicit versions and references to libraries.

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @glennw

[Review on Reviewable](https://reviewable.io/reviews/servo/gleam/45)

### CODE REVIEW

**Comment by glennw** [comment]
Should this also bump the crate version number so it can be published?

**Comment by larsbergstrom** [comment]
@glennw Should be set now!

**Comment by glennw** [comment]
@larsbergstrom Looks good to me - although it won't merge with that travis failure - not sure what the cause is of that?

**Comment by larsbergstrom** [comment]
OK, figured out what the problem here is. The pre-0.1 versions of gl_generator had a wildcard dependency on xml_rs, which is a bit broken on head. At 0.1.0, gl_generator is pinned to a version works.

We didn't hit this in Servo because Cargo.lock pins xml_rs to a compatible version.

**Pull request merged**
